In [2]:
import pandas as pd
import numpy as np
import xgboost as xgb
import lightgbm as lgb

In [3]:
train = pd.read_csv('./data/jinnan_round1_train_20181227.csv', encoding='gb18030')
test = pd.read_csv('./data/jinnan_round1_testA_20181227.csv', encoding='gb18030')

In [4]:
train.describe()

,A1,A2,A3,A4,A6,A8,A10,A12,A13,A15,...,A27,B1,B2,B3,B6,B8,B12,B13,B14,收率
count,1396.000000,42.0,1354.000000,1396.000000,1396.000000,149.000000,1396.000000,1396.000000,1396.000000,1396.000000,...,1396.000000,1386.000000,1394.000000,1394.000000,1396.000000,1395.000000,1395.000000,1395.000000,1396.000000,1396.000000
mean,298.853868,125.0,403.515510,705.974212,28.287751,78.818792,100.861032,102.641834,0.199907,103.829370,...,74.396848,334.452742,3.454412,3.500072,72.065186,43.709677,1020.215054,0.149419,410.403295,0.923244
std,10.130552,0.0,13.348093,53.214754,6.742765,2.683920,0.905198,0.915387,0.002524,0.963639,...,3.044490,105.120753,0.388585,0.002678,9.161986,4.338396,205.920155,0.008213,26.018410,0.030880
min,200.000000,125.0,270.000000,470.000000,17.000000,70.000000,100.000000,98.000000,0.120000,100.000000,...,45.000000,3.500000,0.150000,3.500000,40.000000,20.000000,400.000000,0.030000,40.000000,0.624000
25%,300.000000,125.0,405.000000,700.000000,24.000000,80.000000,100.000000,102.000000,0.200000,103.000000,...,73.000000,320.000000,3.500000,3.500000,65.000000,45.000000,800.000000,0.150000,400.000000,0.902000
50%,300.000000,125.0,405.000000,700.000000,29.000000,80.000000,101.000000,103.000000,0.200000,104.000000,...,73.000000,320.000000,3.500000,3.500000,78.000000,45.000000,1200.000000,0.150000,400.000000,0.925000
75%,300.000000,125.0,405.000000,700.000000,30.000000,80.000000,102.000000,103.000000,0.200000,104.000000,...,77.000000,330.000000,3.500000,3.500000,80.000000,45.000000,1200.000000,0.150000,420.000000,0.943000
max,300.000000,125.0,405.000000,980.000000,97.000000,82.000000,103.000000,107.000000,0.200000,109.000000,...,80.000000,1200.000000,3.600000,3.600000,80.000000,73.000000,1200.000000,0.150000,460.000000,1.000800

In [5]:
test.describe()

,A1,A2,A3,A4,A6,A8,A10,A12,A13,A15,...,A25,A27,B1,B2,B3,B6,B8,B12,B13,B14
count,150.000000,3.0,147.000000,150.000000,150.000000,18.000000,150.000000,150.000000,1.500000e+02,150.000000,...,149.000000,149.000000,149.000000,150.000000,150.0,150.000000,150.000000,150.000000,1.500000e+02,150.000000
mean,299.333333,125.0,404.081633,704.066667,29.373333,80.111111,100.866667,102.774667,2.000000e-01,103.812667,...,75.436242,74.275168,343.557047,3.433000,3.5,72.073333,43.726667,1016.000000,1.500000e-01,414.733333
std,8.164966,0.0,11.134612,43.782511,8.737443,0.323381,0.924438,0.877855,5.012741e-16,1.125500,...,4.849522,4.021663,125.397066,0.470571,0.0,9.347933,4.247220,208.568145,2.227885e-16,36.535294
min,200.000000,125.0,270.000000,470.000000,18.000000,80.000000,100.000000,101.000000,2.000000e-01,101.000000,...,70.000000,45.000000,190.000000,0.150000,3.5,40.000000,20.000000,400.000000,1.500000e-01,280.000000
25%,300.000000,125.0,405.000000,700.000000,24.000000,80.000000,100.000000,102.000000,2.000000e-01,103.000000,...,70.000000,73.000000,320.000000,3.500000,3.5,65.000000,45.000000,800.000000,1.500000e-01,400.000000
50%,300.000000,125.0,405.000000,700.000000,29.000000,80.000000,101.000000,103.000000,2.000000e-01,104.000000,...,78.000000,73.000000,320.000000,3.500000,3.5,78.000000,45.000000,1200.000000,1.500000e-01,400.000000
75%,300.000000,125.0,405.000000,700.000000,30.000000,80.000000,102.000000,103.000000,2.000000e-01,104.000000,...,80.000000,77.000000,340.000000,3.500000,3.5,80.000000,45.000000,1200.000000,1.500000e-01,420.000000
max,300.000000,125.0,405.000000,980.000000,80.000000,81.000000,103.000000,106.000000,2.000000e-01,107.000000,...,90.000000,80.000000,1200.000000,3.500000,3.5,80.000000,50.000000,1200.000000,1.500000e-01,785.000000